(function () {
  'use strict';

  const levels = [
    { n: 1, cols: 5, rows: 5, colors: 4, stones: 0, moves: 20, goal: { type: 'score', target: 600, reward: 200 } },
    { n: 2, cols: 5, rows: 5, colors: 4, stones: 0, moves: 20, goal: { type: 'color', color: 0, target: 6, reward: 230 } },
    { n: 3, cols: 5, rows: 5, colors: 4, stones: 0, moves: 20, goal: { type: 'color', color: 1, target: 7, reward: 250 } },
    { n: 4, cols: 5, rows: 5, colors: 4, stones: 0, moves: 21, goal: { type: 'combo', target: 1, reward: 280 } },
    { n: 5, cols: 5, rows: 5, colors: 4, stones: 0, moves: 21, goal: { type: 'score', target: 1000, reward: 300 } },
    { n: 6, cols: 5, rows: 5, colors: 4, stones: 0, moves: 21, goal: { type: 'color', color: 2, target: 8, reward: 320 } },
    { n: 7, cols: 5, rows: 5, colors: 4, stones: 0, moves: 22, goal: { type: 'special', target: 1, reward: 340 } },
    { n: 8, cols: 5, rows: 5, colors: 4, stones: 0, moves: 22, goal: { type: 'special', target: 1, reward: 370 } },
    { n: 9, cols: 5, rows: 5, colors: 4, stones: 0, moves: 22, goal: { type: 'color', color: 3, target: 10, reward: 390 } },
    { n: 10, cols: 5, rows: 5, colors: 4, stones: 0, moves: 23, goal: { type: 'score', target: 1500, reward: 410 } },
    { n: 11, cols: 6, rows: 6, colors: 4, stones: 0, moves: 23, goal: { type: 'score', target: 1800, reward: 430 } },
    { n: 12, cols: 6, rows: 6, colors: 4, stones: 0, moves: 23, goal: { type: 'color', color: 0, target: 12, reward: 450 } },
    { n: 13, cols: 6, rows: 6, colors: 4, stones: 0, moves: 24, goal: { type: 'combo', target: 2, reward: 470 } },
    { n: 14, cols: 6, rows: 6, colors: 5, stones: 0, moves: 24, goal: { type: 'color', color: 1, target: 12, reward: 490 } },
    { n: 15, cols: 6, rows: 6, colors: 5, stones: 0, moves: 24, goal: { type: 'special', target: 2, reward: 510 }, boosters: ['hammer'] },
    { n: 16, cols: 6, rows: 6, colors: 5, stonesStart: 2, stoneSpawnChance: 0.02, stoneSpawnMax: 6, moves: 25, goal: { type: 'stones', target: 2, reward: 530 }, boosters: ['hammer'] },
    { n: 17, cols: 6, rows: 6, colors: 5, stonesStart: 2, stoneSpawnChance: 0.02, stoneSpawnMax: 6, moves: 25, goal: { type: 'color', color: 2, target: 14, reward: 550 }, boosters: ['hammer'] },
    { n: 18, cols: 6, rows: 6, colors: 5, stonesStart: 3, stoneSpawnChance: 0.02, stoneSpawnMax: 7, moves: 25, goal: { type: 'stones', target: 3, reward: 570 }, boosters: ['hammer'] },
    { n: 19, cols: 6, rows: 6, colors: 5, stonesStart: 3, stoneSpawnChance: 0.02, stoneSpawnMax: 7, moves: 26, goal: { type: 'score', target: 2800, reward: 590 }, boosters: ['hammer'] },
    { n: 20, cols: 6, rows: 6, colors: 5, stonesStart: 3, stoneSpawnChance: 0.03, stoneSpawnMax: 8, moves: 26, goal: { type: 'stones', target: 4, reward: 610 }, boosters: ['hammer'] },
    { n: 21, cols: 7, rows: 7, colors: 5, stonesStart: 4, stoneSpawnChance: 0.03, stoneSpawnMax: 9, moves: 27, goal: { type: 'score', target: 3600, reward: 630 }, boosters: ['hammer'] },
    { n: 22, cols: 7, rows: 7, colors: 5, stonesStart: 4, stoneSpawnChance: 0.03, stoneSpawnMax: 9, moves: 27, goal: { type: 'color', color: 3, target: 16, reward: 650 }, boosters: ['hammer'] },
    { n: 23, cols: 7, rows: 7, colors: 5, stonesStart: 4, stoneSpawnChance: 0.03, stoneSpawnMax: 10, moves: 27, goal: { type: 'combo', target: 3, reward: 660 }, boosters: ['hammer'] },
    { n: 24, cols: 7, rows: 7, colors: 5, stonesStart: 4, stoneSpawnChance: 0.04, stoneSpawnMax: 10, moves: 28, goal: { type: 'special', target: 2, reward: 680 }, boosters: ['hammer', 'bomb'] },
    { n: 25, cols: 7, rows: 7, colors: 5, stonesStart: 4, stoneSpawnChance: 0.04, stoneSpawnMax: 11, moves: 28, goal: { type: 'stones', target: 5, reward: 700 }, boosters: ['hammer', 'bomb'] },
    { n: 26, cols: 7, rows: 7, colors: 5, stonesStart: 5, stoneSpawnChance: 0.04, stoneSpawnMax: 12, moves: 28, goal: { type: 'color', color: 0, target: 18, reward: 720 }, boosters: ['hammer', 'bomb'] },
    { n: 27, cols: 7, rows: 7, colors: 5, stonesStart: 5, stoneSpawnChance: 0.04, stoneSpawnMax: 12, moves: 29, goal: { type: 'special', target: 2, reward: 740 }, boosters: ['hammer', 'bomb'] },
    { n: 28, cols: 7, rows: 7, colors: 5, stonesStart: 5, stoneSpawnChance: 0.05, stoneSpawnMax: 13, moves: 29, goal: { type: 'score', target: 5200, reward: 760 }, boosters: ['hammer', 'bomb'] },
    { n: 29, cols: 7, rows: 7, colors: 5, stonesStart: 5, stoneSpawnChance: 0.05, stoneSpawnMax: 13, moves: 29, goal: { type: 'stones', target: 7, reward: 780 }, boosters: ['hammer', 'bomb'] },
    { n: 30, cols: 7, rows: 7, colors: 5, stonesStart: 5, stoneSpawnChance: 0.05, stoneSpawnMax: 14, moves: 30, goal: { type: 'createRainbow', target: 1, reward: 800 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 31, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.05, stoneSpawnMax: 14, moves: 30, goal: { type: 'score', target: 6400, reward: 810 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 32, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.05, stoneSpawnMax: 14, moves: 30, goal: { type: 'color', color: 1, target: 22, reward: 830 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 33, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.06, stoneSpawnMax: 15, moves: 30, goal: { type: 'stones', target: 9, reward: 850 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 34, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.06, stoneSpawnMax: 15, moves: 31, goal: { type: 'combo', target: 4, reward: 870 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 35, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.06, stoneSpawnMax: 16, moves: 31, goal: { type: 'special', target: 3, reward: 890 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 36, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.06, stoneSpawnMax: 16, moves: 31, goal: { type: 'color', color: 2, target: 24, reward: 910 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 37, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 17, moves: 31, goal: { type: 'stones', target: 11, reward: 920 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 38, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 17, moves: 32, goal: { type: 'score', target: 8400, reward: 940 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 39, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 18, moves: 32, goal: { type: 'special', target: 4, reward: 960 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 40, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 18, moves: 32, goal: { type: 'stones', target: 13, reward: 980 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 41, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 18, moves: 33, goal: { type: 'color', color: 0, target: 26, reward: 1000 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 42, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 19, moves: 33, goal: { type: 'combo', target: 5, reward: 1010 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 43, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 19, moves: 33, goal: { type: 'stones', target: 14, reward: 1030 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 44, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 20, moves: 34, goal: { type: 'score', target: 10400, reward: 1050 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 45, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 20, moves: 34, goal: { type: 'rainbowUse', target: 1, reward: 1070 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 46, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 20, moves: 34, goal: { type: 'stones', target: 16, reward: 1090 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 47, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 21, moves: 35, goal: { type: 'special', target: 5, reward: 1100 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 48, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 21, moves: 35, goal: { type: 'stones', target: 17, reward: 1120 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 49, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 22, moves: 35, goal: { type: 'score', target: 13000, reward: 1140 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 50, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 22, moves: 36, goal: { type: 'score', target: 15000, reward: 1160 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 51, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.06, stoneSpawnMax: 20, moves: 35, goal: { type: 'color', color: 0, target: 28, reward: 1170 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 52, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.06, stoneSpawnMax: 20, moves: 35, goal: { type: 'combo', target: 5, reward: 1190 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 53, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.06, stoneSpawnMax: 21, moves: 36, goal: { type: 'stones', target: 18, reward: 1210 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 54, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.06, stoneSpawnMax: 21, moves: 36, goal: { type: 'score', target: 16000, reward: 1230 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 55, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 21, moves: 36, goal: { type: 'special', target: 5, reward: 1240 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 56, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 22, moves: 36, goal: { type: 'color', color: 1, target: 28, reward: 1260 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 57, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 22, moves: 37, goal: { type: 'stones', target: 18, reward: 1280 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 58, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 22, moves: 37, goal: { type: 'rainbowUse', target: 1, reward: 1300 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 59, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.07, stoneSpawnMax: 23, moves: 37, goal: { type: 'combo', target: 6, reward: 1310 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 60, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 23, moves: 38, goal: { type: 'score', target: 19000, reward: 1330 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 61, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 23, moves: 37, goal: { type: 'color', color: 4, target: 30, reward: 1350 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 62, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 24, moves: 37, goal: { type: 'createRainbow', target: 1, reward: 1360 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 63, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 24, moves: 38, goal: { type: 'stones', target: 17, reward: 1380 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 64, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 24, moves: 38, goal: { type: 'combo', target: 6, reward: 1400 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 65, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.08, stoneSpawnMax: 25, moves: 38, goal: { type: 'special', target: 6, reward: 1420 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 66, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 25, moves: 39, goal: { type: 'color', color: 0, target: 30, reward: 1430 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 67, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 25, moves: 39, goal: { type: 'score', target: 21000, reward: 1450 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 68, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 26, moves: 39, goal: { type: 'stones', target: 18, reward: 1470 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 69, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 26, moves: 40, goal: { type: 'rainbowUse', target: 2, reward: 1480 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 70, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 26, moves: 40, goal: { type: 'score', target: 23000, reward: 1500 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 71, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.09, stoneSpawnMax: 27, moves: 39, goal: { type: 'color', color: 3, target: 32, reward: 1520 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 72, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.1, stoneSpawnMax: 27, moves: 39, goal: { type: 'special', target: 6, reward: 1530 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 73, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.1, stoneSpawnMax: 27, moves: 40, goal: { type: 'stones', target: 19, reward: 1550 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 74, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.1, stoneSpawnMax: 28, moves: 40, goal: { type: 'color', color: 2, target: 32, reward: 1570 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 75, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.1, stoneSpawnMax: 28, moves: 40, goal: { type: 'createRainbow', target: 2, reward: 1590 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 76, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.1, stoneSpawnMax: 28, moves: 41, goal: { type: 'score', target: 25000, reward: 1600 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 77, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.1, stoneSpawnMax: 29, moves: 41, goal: { type: 'stones', target: 20, reward: 1620 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 78, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.11, stoneSpawnMax: 29, moves: 41, goal: { type: 'combo', target: 7, reward: 1640 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 79, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.11, stoneSpawnMax: 29, moves: 42, goal: { type: 'special', target: 7, reward: 1650 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 80, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.11, stoneSpawnMax: 30, moves: 42, goal: { type: 'score', target: 27000, reward: 1670 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 81, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.11, stoneSpawnMax: 30, moves: 41, goal: { type: 'color', color: 1, target: 34, reward: 1690 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 82, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.11, stoneSpawnMax: 30, moves: 41, goal: { type: 'rainbowUse', target: 2, reward: 1700 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 83, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.11, stoneSpawnMax: 31, moves: 42, goal: { type: 'stones', target: 21, reward: 1720 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 84, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.12, stoneSpawnMax: 31, moves: 42, goal: { type: 'score', target: 29000, reward: 1740 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 85, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.12, stoneSpawnMax: 31, moves: 42, goal: { type: 'color', color: 0, target: 34, reward: 1750 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 86, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.12, stoneSpawnMax: 32, moves: 43, goal: { type: 'special', target: 7, reward: 1770 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 87, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.12, stoneSpawnMax: 32, moves: 43, goal: { type: 'combo', target: 8, reward: 1790 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 88, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.12, stoneSpawnMax: 32, moves: 43, goal: { type: 'stones', target: 22, reward: 1800 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 89, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.12, stoneSpawnMax: 33, moves: 44, goal: { type: 'createRainbow', target: 2, reward: 1820 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 90, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.13, stoneSpawnMax: 33, moves: 44, goal: { type: 'score', target: 32000, reward: 1840 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 91, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.13, stoneSpawnMax: 33, moves: 43, goal: { type: 'color', color: 2, target: 36, reward: 1850 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 92, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.13, stoneSpawnMax: 34, moves: 43, goal: { type: 'stones', target: 23, reward: 1870 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 93, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.13, stoneSpawnMax: 34, moves: 44, goal: { type: 'color', color: 4, target: 36, reward: 1890 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 94, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.13, stoneSpawnMax: 34, moves: 44, goal: { type: 'special', target: 8, reward: 1900 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 95, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.13, stoneSpawnMax: 35, moves: 44, goal: { type: 'rainbowUse', target: 2, reward: 1920 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 96, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.14, stoneSpawnMax: 35, moves: 45, goal: { type: 'score', target: 35000, reward: 1930 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 97, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.14, stoneSpawnMax: 35, moves: 45, goal: { type: 'stones', target: 24, reward: 1950 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 98, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.14, stoneSpawnMax: 36, moves: 45, goal: { type: 'combo', target: 9, reward: 1970 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 99, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.14, stoneSpawnMax: 36, moves: 46, goal: { type: 'special', target: 9, reward: 1980 }, boosters: ['hammer', 'bomb', 'rainbow'] },
    { n: 100, cols: 7, rows: 8, colors: 5, stonesStart: 5, stoneSpawnChance: 0.15, stoneSpawnMax: 37, moves: 46, goal: { type: 'score', target: 40000, reward: 2000 }, boosters: ['hammer', 'bomb', 'rainbow'] }
  ];

  window.CrystalMatchLevels = {
    shuffleGraceUntil: 25,
    staticCount: levels.length,
    levels
  };
})();


